# Generated by Django 4.2 on 2023-05-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spare_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare_part.make')),
                ('modelcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare_part.modelcar')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
